### ISSUE TITLE
requestKeyPress() improper handling when alternate format used

### ISSUE THREAD

**Issue by hufftheweevil** [Pmant/harmonyhubws#1]
First off, great work on this module! I saw all the other simple Harmony websocket packages and thought about making something that was a bit more user friendly and straight forward. Then I found this and it's almost exactly what I envisioned.

I like the dual use of your `requestKeyPress()` method. However, I see two small issues with it.

1. Because of how you test the first parameter for string/number, that means the user must convert the `deviceId` to a number (because it is always given in the `config` as a string. That's not a big deal, but it creates a bigger problem in number 2...

2. If a number is passed as the first parameter, it passes that number into the `JSON.stringify()` call that creates the action code. But it needs to be a string, in double quotes.

I think a simple solution to both of these issues is to just accept a string as the `deviceId` first parameter, then within your code, take that string parameter and see if it's really just a number in disguise (`deviceId == +deviceId`, or there's probably a better way to test it). If it's a number, than use the deviceId/keyId version, otherwise, use the action version.

Also - the `keyId` should be a string as well, not a number.

Edit: I created a PR if you want to easily change it to my suggestion above. If not, no worries.

**Comment by Pmant** [comment]
Makes sense, thank you! Will merge your PR tomorrow.

**Comment by hufftheweevil** [comment]
Just curious if there is any reason this hasn't been merged yet?

**Comment by Pmant** [comment]
I'm sorry I totally forgot about this, thanks for the reminder.
